after-login-command = []
after-startup-command = ["exec-and-forget", "layout tiles"]
exec-on-workspace-change = [
  "/bin/bash",
  "-c",
  "FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE"
]
start-at-login = true
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
automatically-unhide-macos-hidden-apps = true
accordion-padding = 30
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
key-mapping.preset = "qwerty"
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.right = 0
outer.bottom = 0
outer.top = 0

[workspace-to-monitor-force-assignment]
1 = "main"  # Main Monitor
2 = "built-in"  # Built-in Display: MacBook

[mode.main.binding]
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"
alt-e = "layout tiles horizontal vertical"  # 'layout toggle split' in i3
alt-shift-minus = "resize smart -50"
alt-shift-equal = "resize smart +50"
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-7 = "workspace 7"
alt-8 = "workspace 8"
alt-9 = "workspace 9"
alt-0 = "workspace 10"
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-5 = "move-node-to-workspace 5"
alt-shift-6 = "move-node-to-workspace 6"
alt-shift-7 = "move-node-to-workspace 7"
alt-shift-8 = "move-node-to-workspace 8"
alt-shift-9 = "move-node-to-workspace 9"
alt-shift-0 = "move-node-to-workspace 10"
alt-shift-c = "reload-config"
alt-r = "mode resize"

[mode.resize.binding]
h = "resize width -50"
j = "resize height +50"
k = "resize height -50"
l = "resize width +50"
enter = "mode main"
esc = "mode main"
alt-tab = "workspace-back-and-forth"
alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
alt-shift-semicolon = "mode service"

[mode.service.binding]
esc = ["reload-config", "mode main"]
r = ["flatten-workspace-tree", "mode main"]  # reset layout
f = ["layout floating tiling", "mode main"]
backspace = ["close-all-windows-but-current", "mode main"]
alt-shift-h = ["join-with left", "mode main"]
alt-shift-j = ["join-with down", "mode main"]
alt-shift-k = ["join-with up", "mode main"]
alt-shift-l = ["join-with right", "mode main"]

[[on-window-detected]]
check-further-callbacks = true
run = "layout tiling"

[[on-window-detected]]
if.app-id = "com.apple.finder"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "com.apple.mail"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "com.apple.systempreferences"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = ["layout tiling", "move-node-to-workspace 1"]

[[on-window-detected]]
if.app-id = "com.apple.TextEdit"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "com.apple.ActivityMonitor"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "com.apple.findmy"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "com.apple.Home"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "com.apple.MobileSMS"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "com.apple.Preview"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "md.obsidian"
run = ["layout tiling", "move-node-to-workspace 5"]

[[on-window-detected]]
if.app-id = "company.thebrowser.Browser"
run = ["layout tiling", "move-node-to-workspace 4"]

[[on-window-detected]]
if.app-id = "app.zen-browser.zen"
run = ["layout tiling", "move-node-to-workspace 4"]

[[on-window-detected]]
if.app-id = "net.imput.helium"
run = ["layout tiling", "move-node-to-workspace 4"]

[[on-window-detected]]
if.app-id = "com.apple.UserNotificationCenter"
run = ["layout floating"]
